permalink: /posts/:title/
title : OpenCPU
description: "OpenCPU is a framework for embedded scientific computing and reproducible research."
disqus_shortname: opencpu
analytics: UA-701288-6
production_url: https://www.opencpu.org
url: https://www.opencpu.org
thumb : mediumlogo.jpg
author :
  name : Jeroen Ooms
  github : jeroenooms
  twitter : opencpu
  email: jeroen.ooms@stat.ucla.edu
gems:
  - jekyll-redirect-from
future: true
